### ISSUE TITLE
Stable build and docker image

### ISSUE THREAD

**Issue by ErwinSteffens** [Vetal1977/maxctrl_exporter#1]
Hi, just curious on how stable this project is and what the plans are. We are looking for an exporter for MaxScale v2.3. 

I have tried to add a patch to this (https://github.com/RubenHoms/maxscale_exporter) exporter for v2.3, but as you mentioned the max-info api is being deprecated, so this feels like a better way forward. 

Is it possible to create (and tag) a docker image for this? I think it can be done pretty easily with Docker Hub automated builds (https://docs.docker.com/docker-hub/builds/) and a multi-stage image stage for building the binary.  

We can build it ourself if needed, but I would prefer to use a supplied one.

**Comment by ktugan** [comment]
Hey @ErwinSteffens, the project is unstable for now. We don't use it in production yet so its unclear how it will behave under real life load.

Uploading and building the docker image to docker hub we will do but will take more time due to constraints at work. Until then I would ask to build it yourself.

**Comment by ErwinSteffens** [comment]
Ok, thnx for the update. We will first try the other exporter first as we are still on v2.3 for now, but I will watch this project to see when it will be stable.

**Comment by Artanicus** [comment]
As of #9 images are now available on GitHub, so latest would be: `ghcr.io/vetal1977/maxctrl_exporter:latest`

**Comment by ktugan** [comment]
Closing this issue as @Artanicus implemented the docker image. Thanks for that!
