### ISSUE TITLE
Releasing

### ISSUE THREAD

**Issue by mfouilleul** [Vetal1977/maxctrl_exporter#2]
Hello,

Do you plan to create a release or to push into the Docker hub?

Thanks. 

Max.

**Comment by Vetal1977** [comment]
Hey Max,

As @ktugan mentioned [here](https://github.com/Vetal1977/maxctrl_exporter/issues/1#issuecomment-535494403), the project is unstable for now and we don't use it in production yet. 
We plan to release it and upload a Docker image but due constraints at work, cannot do it now.

Vitaly

**Comment by mfouilleul** [comment]
Ok. No problem.
