### ISSUE TITLE
contributing to project

### ISSUE THREAD

**Issue by rvlane** [Vetal1977/maxctrl_exporter#4]
I work for Nokia and we are moving to maxscale-2.5.  Therefore we need an exporter that uses the 8989 maxctrl interface, thus we were looking at this project.  As we are testing we have a couple of major requirements:

1. maxscale passwords must not be exposed via any environment variable or text files.  We are still working how we would accomplish this.
2. We are required to use TLS for all interfaces, including (a) the maxctrl 8989 port (maxscale is configured with TLS for the maxctrl port) and (b) the scraping port (for us 9195).

The older maxscale exporter we were using does not support https either, but we need to have this integrated.  So are you open to additional contributors to this project to implement capabilities that will meet out needs?  I need to get it cleared through the Nokia process, however wanted to check here first.

**Comment by Vetal1977** [comment]
Hi @rvlane .Me and @ktugan will be happy if you contribute to the project. Feel free to makes the changes and open a PR. 
Currently, I just don't have time to implement feature requests :-(

**Comment by Vetal1977** [comment]
@rvlane I hope, you wouldn't mind if I close the issue
