### ISSUE TITLE
Connect to secure admin api

### ISSUE THREAD

**Issue by pgporada** [Vetal1977/maxctrl_exporter#6]
This exporter doesn't appear to be able to connect to maxscale when the REST API has a TLS certificate. In my testing case I'm running maxscale on 0.0.0.0:8989 with a TLS cert and I tell maxctrl to connect to the SAN which is `server.example.com`
```
maxctrl --secure --tls-ca-cert /etc/maxscale/tls/ca.cert --hosts $(hostname):8989 list servers
```

Do I always need to send a username/password when running the exporter?

**Comment by Vetal1977** [comment]
@pgporada I have implemented [basic authentication only](https://github.com/Vetal1977/maxctrl_exporter/blob/8182b8d851ff23ecf3d400cb743b205e32de8867/maxctrl_exporter.go#L135). So yes - you need to send a username and password. TLS requires some work (as described, e.g., [here](https://youngkin.github.io/post/gohttpsclientserver/#create-the-client)). Though, I am not sure if I can find time in the next couple of weeks 😞

**Comment by pgporada** [comment]
Thanks for the link. What I've ended up doing is copying most of the consul_exporter guts and am slowly trying to rebuild what you've done here on top of that code. It's ... going.
